#88 map parsing
moevm/mse_visual_map_editor_for_duckietown pull request #102
Opened 2020-08-20 20:14 UTC by snush

#88

2020-08-20 21:10 UTC, HadronCollider requested changes

2020-08-20 21:10 UTC, HadronCollider commented on IOManager.py
> +        parent.map.gridSize = 100 * data_from_file(input_map).get('tile_size')
Предлагаю перенести функциональность по обработке в соответствующие методы `*_to_objetcs`

- в `tiles_to_objects` добавить
https://github.com/moevm/mse_visual_map_editor_for_duckietown/blob/80e1806967673e6da3b5623c40c07af1ba67aa16/map_parser.py#L358-L366
тем самым избавившись от вызова `get_tiles`
- в `map_objects_to_objects` добавить
https://github.com/moevm/mse_visual_map_editor_for_duckietown/blob/80e1806967673e6da3b5623c40c07af1ba67aa16/map_parser.py#L403-L406
тем самым избавившись от вызова `get_objects`

После этого данные строки можно заменить на:
```python3
map_info = data_from_file(input_map)		# загрузка файла в dict()
parent.map.set_tile_layer(tiles_to_objects((map_info['tiles']))		# обработка и добавление `tiles`
parent.map.set_item_layer(map_objects_to_objects(map_info['objects']))		# обработка и добавление `objects`
parent.map.gridSize = 100 * map_info['tile_size']
```

Задумка в том, чтобы уменьшить количество вызовов `data_from_file` до минимального одного раза и убрать функции `get_tiles/get_objects/get_tile_size` вовсе.

2020-08-20 21:10 UTC, HadronCollider commented on map_parser.py
> +                value['static'] = 'True'
Кажется, это ошибочная обработка (оставшаяся после создателей), `optional/static` должны быть bool

Замените `'false' -> False` и `'True' -> True` соответственно

2020-08-20 21:10 UTC, HadronCollider commented on tests/parser_test.py
> +                               # {'kind': 'straight', 'rotate': 270}, {'kind': 'asphalt', 'rotate': 0},
Зачем эта строка помещена в комментарии?

2020-08-20 21:10 UTC, HadronCollider commented on map_parser.py
>          optional = True if object['optional'] == 'true' else False
Последствия, можно заменить на
```python
optional = object['optional']
static = object['static']
```
после исправления 

Ещё более уместным вариантом будет:
```python
for object in map_objects:
	map_objects_array.append(MapObject(kind=object['kind'], position=object['pos'], 
		rotation=object['rotate'], height=object['height'], optional=object['optional'],
		static=object['static']))
```
- \+ отсутствие ненужных локальных переменных
- \+ использование именованных аргументов
- \- слегка пониженная читабельность

2020-08-21 07:09 UTC, HadronCollider commented
Добавьте `yaml` (с указанием версии) в https://github.com/moevm/mse_visual_map_editor_for_duckietown/blob/devel/requirements.txt

2020-08-21 07:25 UTC, HadronCollider commented
Модифицируйте функцию сохранения карты с использованием yaml
https://github.com/moevm/mse_visual_map_editor_for_duckietown/blob/bedae9956b31807145322f3e172c081d3ef0425b/map_parser.py#L275

2020-08-25 20:03 UTC, HadronCollider approved these changes

2020-08-26 06:58 UTC, light5551 approved these changes

2020-08-26 06:59 UTC, merged