super class for maptile and mapobject
moevm/mse_visual_map_editor_for_duckietown pull request #120
Opened 2020-08-26 16:13 UTC by light5551

#111

2020-08-26 16:59 UTC, HadronCollider requested changes

2020-08-26 16:59 UTC, HadronCollider commented on classes/baseClass.py
> +        self.rotation = rotation
По поводу `rotation`, с одной стороны, не все объекты его имеют (например, сторожевые башни), и иметь это поле для подобных объектов - лишнее, с другой большая часть наследуемых от `BaseEditorClass` классов имеют данный параметр, и добавлять его в каждый дочерный класс, кажется, неразумным.

2020-08-26 16:59 UTC, HadronCollider commented on classes/mapObjects.py
> +        self.position['x'], self.position['y'] = position
Возможно, стоит перейти к формату хранения в виде `[x, y]`, как более "лёгкой" конструкции (особенно в плане памяти)

2020-08-26 16:59 UTC, HadronCollider commented on classes/mapObjects.py
> +        MapBaseObject.__init__(self, kind, **kwargs)
А точно ли существует потребность в отдельных классах `SignObject/CityObject/GroundAprilTagObject` или же можно обойтись одним классом для подобных объектов (пока особых различий между ними не предвидится)

2020-08-26 16:59 UTC, HadronCollider commented on classes/mapObjects.py
> +        self.hostname = kwargs["hostname"]
Кажется, что при таком наследовании `WatchTowerObject` имеет очень много лишних параметров
- rotation
- optional 
- static 
- height (возможно)

2020-08-26 16:59 UTC, HadronCollider commented on classes/mapObjects.py
> +        }.items()
Стоит проверить (по текущему стандарту карт) являются ли `optional/static` обязательными для указания - возможно, у них есть значения по умолчанию, которые не добавляются
https://github.com/moevm/mse_visual_map_editor_for_duckietown/blob/7b894a84f603e678d64916160f3671ca8e3fd23c/map_parser.py#L304-L307

2020-08-26 16:59 UTC, HadronCollider commented on classes/mapObjects.py
> +        }.items()
Метод `__iter__` (необязательно сейчас, возможно, позже - когда структура и необходимые поля будут точно известны) лучше определить для каждого дочернего класса.
Сейчас для `WatchTowerObject`, к примеру, не будет получен параметр `hostname`

2020-08-26 16:59 UTC, HadronCollider commented on mainwindow.py
> +                self.map.add_item(MapObject(item_name)) # TODO: need to understand what's the type and create desired class, not general
Скорее всего понадобится фабрика или конструктор #118 #121

2020-08-26 18:12 UTC, light5551 commented on classes/baseClass.py
> +        self.rotation = rotation
watchtower как я понимаю имеют угол, в зависимости от угла понятно на какой участок карты смотрит камера, то есть имеет значение

2020-08-26 18:24 UTC, light5551 commented on classes/mapObjects.py
> +        self.hostname = kwargs["hostname"]
по поводу rotation написал [здесь](https://github.com/moevm/mse_visual_map_editor_for_duckietown/pull/120#discussion_r477493808). По поводу static если я не ошибаюсь, то он должен отвечать за [можно двигать|нельзя двигать]. То есть это спорный момент. Возможным решением будет наследования от `BaseEditorClass`, но я думаю, что ничего страшного, если класс будет хранить несколько лишних полей

2020-08-26 18:24 UTC, light5551 commented on classes/mapObjects.py
> +        MapBaseObject.__init__(self, kind, **kwargs)
Возможно в будущем эти классы будут отличаться полями, к примеру класс `GroundAprilTagObject` возможно в будущем будет иметь поле `tagid` из `tag36h11`

2020-08-26 18:25 UTC, light5551 commented on classes/mapObjects.py
> +        MapBaseObject.__init__(self, kind, **kwargs)
И разве мы не говорили, что в каждом слое будут объекты своего типа?

2020-08-26 18:32 UTC, HadronCollider commented on classes/mapObjects.py
> +        MapBaseObject.__init__(self, kind, **kwargs)
Может неверно друг друга поняли, но, кажется, что максимальное обобщение объектов слоев позволит увеличивать кол-во слоев (в случае необходимости) - жесткая привязка класса к слою ухудшает гибкость.

Хотя касательно новый полей, наверно, правильно - всю информацию о теге в kind/id поместить не удастся.

Пока можем оставить так - в дальйнейшем станет яснее

2020-08-26 19:19 UTC, light5551 commented on classes/mapObjects.py
> +        self.position['x'], self.position['y'] = position
Предлагаю пока оставить так, а потом используя `@property` возвращать словарь position(также как сейчас это и используется во всем остальном приложении) + а хранение сделать через массив -  то есть в отдельную задачу это поместить

2020-08-27 07:15 UTC, HadronCollider approved these changes

2020-08-27 10:04 UTC, merged